Merge pull request #3 from PolinKartav
PolinKartav/java-explore-with-me pull request #4
Opened 2023-10-04 14:33 UTC by PolinKartav

feat: added main-server

2023-10-05 20:19 UTC, alexache requested changes

2023-10-05 20:19 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/CategoryServiceImpl.java
> +            throw new AlreadyExistedException("Category with ID = " + catId + " already used.");
Текст ошибки, пожалуй, не подходит к самой причине исключения

2023-10-05 20:19 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/RequestServiceImpl.java
> +    public Request makeRequest(Event event, User user) {
Это точно публичный метод?

2023-10-05 20:19 UTC, alexache commented on main/main-server/src/main/resources/schema.sql
> +    confirmed_requests BIGINT  DEFAULT 0,
Это и следующее поле лишние в данной таблице

2023-10-05 20:19 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/EventServiceImpl.java
> +    public List<ParticipationRequestDto> getRequests(Long eventId, Long userId) {
А почему это не в сервисе запросов?

2023-10-05 20:19 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/EventServiceImpl.java
> +        Event event = query
Немного выглядит усложнением, можно просто брать какую-то дату в прошлом, иначе возникают большие вопросы, почему сервис создает запросы к базе даннх в обход репозиториев, нарушение принципа single responsibility

2023-10-07 18:06 UTC, PolinKartav commented on main/application/src/main/java/ru/practicum/ewm/main/application/event/EventUpdateRequest.java
> +public class EventUpdateRequest {
Это базовый класс, в нем не нужна валидация, по моему мнению

2023-10-07 18:15 UTC, PolinKartav commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/entity/Event.java
> +    private Long views;
views удалила, а ConfirmedRequests понижена нормализация базы данных для сокращения количества обращений к базе данных

2023-10-07 18:18 UTC, PolinKartav commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/entity/Compilation.java
> +    Boolean pinned;
Добавлено

2023-10-07 18:24 UTC, PolinKartav commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/CategoryServiceImpl.java
> +            throw new AlreadyExistedException("Category with ID = " + catId + " already used.");
Спасибо, поправила

2023-10-07 18:25 UTC, PolinKartav commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/RequestServiceImpl.java
> +    public Request makeRequest(Event event, User user) {
исправила на private

2023-10-07 18:27 UTC, PolinKartav commented on main/main-server/src/main/resources/schema.sql
> +    confirmed_requests BIGINT  DEFAULT 0,
views удалила, а ConfirmedRequests оставила по причине, описанной выше

2023-10-07 18:31 UTC, PolinKartav commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/EventServiceImpl.java
> +    public List<ParticipationRequestDto> getRequests(Long eventId, Long userId) {
перенесла в сервис request

2023-10-07 18:36 UTC, PolinKartav commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/EventServiceImpl.java
> +        Event event = query
Во всем проекте применяется QueryDSL. Считаю корректно получать самую раннюю дату создания из списка эвентов.

2023-10-09 05:35 UTC, alexache commented on main/application/src/main/java/ru/practicum/ewm/main/application/event/EventUpdateRequest.java
> +public class EventUpdateRequest {
ок, тогда зачем этот базовый класс? зачем два других его расширяют и переопределяют те же поля?

2023-10-09 05:38 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/entity/Event.java
> +    private Long views;
и целостность данных приносится в жертву, это не тот способ

2023-10-09 05:39 UTC, alexache requested changes

2023-10-09 05:39 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/EventServiceImpl.java
> +        Event event = query
Тогда перенести это в репозиторий из сервиса

2023-10-09 19:58 UTC, PolinKartav commented on main/application/src/main/java/ru/practicum/ewm/main/application/event/EventUpdateRequest.java
> +public class EventUpdateRequest {
Базовый класс используется для обновления по двум наследникам в имлиментации EventService

2023-10-11 13:25 UTC, alexache approved these changes

2023-10-11 13:25 UTC, alexache commented on main/application/src/main/java/ru/practicum/ewm/main/application/event/EventFullDto.java
> +public class EventFullDto extends EventBaseDto {
Я все равно не понимаю такой иерархии классов: задумка ясна, но реализация вызывает вопросы. Вводится базовый класс с полями - ок, затем наследники зачем-то переопределяют те же поля, для чего это? Теряется смысл базового класса.

2023-10-11 13:25 UTC, alexache commented on main/main-server/src/main/java/ru/practicum/ewm/main/server/service/impl/EventServiceImpl.java
> +        List<Long> ids = list.stream().map(EventBaseDto::getId).collect(Collectors.toList());
(опционально) все еще немного смущает построение запросов в самом сервисе, такое обычно выносят в кастомный репозиторий. Иначе это нарушение single responsibility

2023-10-12 18:25 UTC, merged